/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Ed25519Keypair {
  publicKey: Uint8Array
  privateKey: Uint8Array
}
export function generateKeyPair(): Ed25519Keypair
export function createKeyPair(privateKey: Uint8Array): Ed25519Keypair
export function sign(privateKey: Uint8Array, message: Uint8Array): Uint8Array
export function verify(publicKey: Uint8Array, message: Uint8Array, signatureBuffer: Uint8Array): boolean
