/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createKeyPair(privateKey: Uint8Array): Ed25519Keypair

export interface Ed25519Keypair {
  publicKey: Uint8Array
  privateKey: Uint8Array
}

export declare function generateKeyPair(): Ed25519Keypair

export declare function sign(privateKey: Uint8Array, message: Uint8Array): Uint8Array

export declare function verify(publicKey: Uint8Array, message: Uint8Array, signatureBuffer: Uint8Array): boolean
